# Server
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost/learning_management_system?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:7010812682}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQL8Dialect}
spring.jpa.show-sql=true

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Springfox
spring.mvc.pathmatch.matching-strategy=ant_path_matcher